package com.lingmiao.shop.business.goods.api.bean

data class GoodsWarningVO(
    val `data`: List<Data>,
    val data_total: Int,
    val page_no: Int,
    val page_size: Int
) {

    data class Data(
        val auth_message: Any,
        val available_date: String,
        val big: String,
        val brand_id: Any,
        val buy_count: Int,
        val category_id: Int,
        val comment_num: Int,
        val cost: Any,
        val create_time: Int,
        val disabled: Int,
        val enable_quantity: Int,
        val event_price: Any,
        val event_quantity: Int,
        val expiry_day: Any,
        val freight_pricing_way: Any,
        val freight_unified_price: Int,
        val goods_id: Int,
        val goods_name: String,
        val goods_transfee_charge: Int,
        val goods_type: String,
        val grade: Int,
        val have_spec: Int,
        val intro: Any,
        val is_auth: Int,
        val is_global: Int,
        val is_local: Int,
        val is_self_take: Int,
        val last_modify: Int,
        val local_template_id: Int,
        val market_enable: Int,
        val meta_description: Any,
        val meta_keywords: String,
        val mktprice: Any,
        val original: String,
        val package_price: Int,
        val page_title: String,
        val point: Any,
        val pre_sort: Int,
        val price: Double,
        val quantity: Int,
        val self_operated: Int,
        val seller_id: Int,
        val seller_name: String,
        val selling: String,
        val shop_cat_id: Int,
        val shop_cat_items: String,
        val shop_lat: Any,
        val shop_lng: Any,
        val small: String,
        val sn: String,
        val store: Any,
        val supplier_name: String,
        val template_id: Int,
        val thumbnail: String,
        val under_message: Any,
        val up_goods_id: String,
        val video_url: Any,
        val view_count: Int,
        val weight: Any
    )

}